module Ipgeobase
  VERSION: String
  def self.lookup(ip: String) -> void
  
  class Http
    def get_response(ip: String) -> void
  end

  class Response
    def self.parse(response: String) -> void
  end
end
